apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-sink-config
  namespace: neo4j
data:
  sink.neo4j.json: |
    {
      "name": "Neo4jSinkConnectorJSONString",
      "config": {
        "topics": "nyc_taxicab_data",
        "connector.class": "org.neo4j.connectors.kafka.sink.Neo4jConnector",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "errors.retry.timeout": "-1",
        "errors.retry.delay.max.ms": "1000",
        "errors.tolerance": "all",
        "errors.log.enable": "true",
        "errors.log.include.messages": "true",
        "neo4j.uri": "bolt://neo4j-service:7687",
        "neo4j.authentication.basic.username": "neo4j",
        "neo4j.authentication.basic.password": "changeme",
        "neo4j.cypher.topic.nyc_taxicab_data": "MERGE (p:Location {name: toInteger(__value.PULocationID)}) MERGE (d:Location {name: toInteger(__value.DOLocationID)}) MERGE (p)-[:TRIP {distance: toFloat(__value.trip_distance), fare: toFloat(__value.fare_amount), pickup_dt: datetime(__value.tpep_pickup_datetime), dropoff_dt: datetime(__value.tpep_dropoff_datetime)}]->(d)"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
  namespace: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
      - name: kafka-neo4j-connector
        image: roy012299/kafka-neo4j-connect:latest
        ports:
        - containerPort: 8083
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka-service:29092"
        - name: CONNECT_GROUP_ID
          value: "neo4j-connector-group"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "neo4j-connector-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "neo4j-connector-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "neo4j-connector-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "kafka-neo4j-connector"
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/usr/share/confluent-hub-components"
        - name: CONNECT_LISTENERS
          value: "http://0.0.0.0:8083"
        volumeMounts:
        - name: connector-config
          mountPath: /etc/kafka-connect/sink.neo4j.json
          subPath: sink.neo4j.json
      volumes:
      - name: connector-config
        configMap:
          name: neo4j-sink-config

